admin/__init__.py
from flask import Blueprint

admin_bp= Blueprint('admin', __name__,template_folder='templates')

from . import routes

admin/routes.py
from flask import render_template, request, redirect, url_for, session, flash
from . import admin_bp
from dotenv import load_dotenv
import os

load_dotenv()

SALVATTORE_ADMIN= os.getenv('SALVATTORE_ADMIN')
SALVATTORE_SENHA= os.getenv('SALVATTORE_SENHA')

arq_processos= 'processos.csv'

diretorio_base= os.path.dirname(os.path.abspath(__file__))
arquivo_processos= os.path.join(diretorio_base, '..', 'data', 'processos.csv')

@admin_bp.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        usuario= request.form.get('usuario')
        senha= request.form.get('senha')

        if usuario == SALVATTORE_ADMIN and senha == SALVATTORE_SENHA:
            session['usuario_logado'] = usuario
            flash('Login realizado com sucesso!', 'sucesso')
            return redirect(url_for('admin.gerenciar_processos'))
        else:
            flash('Usuário ou senha incorretos.', 'erro')
    
    return render_template('admin/login.html')


@admin_bp.route('/logout')
def logout():
    session.pop('usuario_logado', None)
    flash('Logout realizado com sucesso!', 'sucesso')
    return redirect(url_for('pagina_principal'))


def ler_processos():

    processos=[]

    with open(arquivo_processos, 'r', encoding='utf-8') as arq:
        linhas = arq.readlines()

        for linha in linhas[1:]:
            linha = linha.strip()
            if not linha:
                continue

            processo_id,titulo,url = linha.split('|')

            processos.append({
                "processo_id": int(processo_id),
                "titulo": titulo,
                "url": url,
            })

    return processos


@admin_bp.route('/processos')
def gerenciar_processos():
    processos= ler_processos()

    if 'usuario_logado' not in session:
        flash('Você não esta logado', 'erro')
        return redirect(url_for('admin.login'))

    return render_template('admin/gerenciar_processos.html', processos= processos)


@admin_bp.route('/novo', methods=['GET','POST'])
def novo_processo():
    
    if 'usuario_logado' not in session:
        flash('Você não está logado.', 'erro')
        return redirect(url_for('admin.login'))
    
    if request.method=='GET':
        return render_template('admin/criar_processo.html')
    
    if request.method=='POST':
        titulo= request.form.get('titulo')
        url= request.form.get('url')

        processos=ler_processos()

        maior_id=0

        for processo in processos:
            if processo['processo_id']>maior_id:
                maior_id=processo['processo_id']
    
        novo_id=maior_id+1

        nova_linha=f"\n{novo_id}|{titulo}|{url}"

        with open(arquivo_processos, 'a', encoding='utf-8') as arq:
            arq.write(nova_linha)
    
    return redirect(url_for('admin.gerenciar_processos'))


@admin_bp.route('/editar/<int:processo_id>', methods=['GET', 'POST'])
def editar_processo(processo_id):

    processos= ler_processos()

    processos_reescrita=[]
    
    if request.method== 'GET':

        processo_encontrado= None

        for processo in processos:
            if processo['processo_id']== processo_id:
                processo_encontrado=processo
                break
        
        return render_template('admin/editar_processo.html', processo=processo_encontrado)
    
    if request.method== 'POST':

        titulo_novo= request.form.get('titulo')
        url_nova= request.form.get('url')


        for processo in processos:
            if processo['processo_id'] != processo_id:
                processos_reescrita.append(processo)
        
        processos_reescrita.append(
            {
                'processo_id': processo_id,
                'titulo': titulo_novo,
                'url': url_nova,
            }
        )
                   
    with open(arquivo_processos, 'w', encoding='utf-8') as arq:
        arq.write("id|titulo|url\n")
        for processo in processos_reescrita:
            linha= f"{processo['processo_id']}|{processo['titulo']}|{processo['url']}\n"
            arq.write(linha)
    
    return redirect(url_for('admin.gerenciar_processos'))


@admin_bp.route('/deletar/<int:processo_id>', methods=['GET', 'POST'])
def deletar_processo(processo_id):

    processos=ler_processos()

    processos_reescrita=[]

    for processo in processos:
        if processo['processo_id'] != processo_id:
            processos_reescrita.append(processo)
    
    with open(arquivo_processos, 'w', encoding='utf-8') as arq:
        arq.write("id|titulo|url\n")
        for processo in processos_reescrita:
            linha= f"{processo['processo_id']}|{processo['titulo']}|{processo['url']}\n"
            arq.write(linha)
    
    return redirect(url_for('admin.gerenciar_processos'))

app.py
from flask import Flask, render_template, request, redirect, url_for, flash
import os
import csv
import requests
from admin.routes import diretorio_base, arquivo_processos, ler_processos

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY")

from admin import admin_bp

app.register_blueprint(admin_bp, url_prefix="/admin")

@app.route("/")
def pagina_principal():
    return render_template("index.html")

@app.route("/contato", methods=["GET", "POST"])
def contato():
    if request.method == "POST":
        nome = request.form["nome"]
        email = request.form["email"]
        telefone = request.form.get("telefone", "")
        assunto = request.form["assunto"]

        caminho_csv = os.path.join("data", "dados.csv")
        arquivo_existe = os.path.isfile(caminho_csv)

        with open(caminho_csv, mode="a", newline="", encoding="utf-8") as arquivo:
            writer = csv.writer(arquivo)

            if not arquivo_existe:
                writer.writerow(["Nome", "Email", "Telefone", "Assunto"])
            
            writer.writerow([nome, email, telefone, assunto])

            flash("Mensagem enviada com sucesso!", "sucesso")
        
        url_webhook = "https://hook.us2.make.com/2co6w7ldul6cv3f8l763ti7pt7exbplj"

        dados = {
            "nome": nome,
            "email": email,
            "telefone": telefone,
            "assunto": assunto
        }

        requests.post(url_webhook, json=dados)

        return redirect(url_for("contato"))
    return render_template("contato.html")

@app.route('/processos')
def processos_seletivos():

    processos= ler_processos()

    return render_template('processos.html', processos=processos)

@app.route("/agendamentos", methods=["GET", "POST"])
def agendamentos():
    if request.method == "POST":
        nome = request.form["nome"]
        email = request.form["email"]
        telefone = request.form["telefone"]
        data = request.form["data"]
        horario = request.form["horario"]
        local = request.form["local"]
        publico = request.form["publico"]
        tema = request.form["tema"]

        caminho_csv = os.path.join("data", "agendamentos.csv")
        arquivo_existe = os.path.isfile(caminho_csv)

        with open(caminho_csv, mode="a", newline="", encoding="utf-8") as arquivo:
            writer = csv.writer(arquivo)

            if not arquivo_existe:
                writer.writerow([
                    "Nome", "Email", "Telefone", "Data",
                    "Horario", "Local", "Publico", "Tema"
                ])

            writer.writerow([
                nome, email, telefone, data,
                horario, local, publico, tema
            ])
        
        url_webhook = "https://hook.us2.make.com/8txrcg0nhsb34h6guoxlz2h28nukfc1s"

        dados = {
            "nome": nome,
            "email": email,
            "telefone": telefone,
            "data": data,
            "horario": horario,
            "local": local,
            "publico": publico,
            "tema": tema
        }

        requests.post(url_webhook, json=dados)

        flash("Agendamento enviado com sucesso!", "sucesso")
        return redirect(url_for("agendamentos"))

    return render_template("agendamentos.html")


if __name__ == "__main__":
    app.run(debug=True)

templates/agendamentos.html
{% extends "base.html" %}

{% block title %}
Contato
{% endblock %}

{% block content %}
<section class="agendamentos">
    <div class="txt-agendamentos">

        <span class="agenda">AGENDA</span>

        <h1>Agendamentos de Palestras</h1>
        <p>
        A página de agendamento de palestras da Salvattore Assessoria foi desenvolvida 
        para facilitar a solicitação de palestras, treinamentos e 
        encontros técnicos voltados à gestão de políticas públicas.
        Por meio dela, gestores, servidores públicos, instituições e organizações 
        podem solicitar palestras, treinamentos e encontros técnicos de forma prática e organizada.
        </p>

        <a href="#form" class="btn-form">Agendar Palestra</a>

    </div><!--txt-agendamentos-->
    <div class="img-agendamentos">
        <img src="{{ url_for('static', filename='images/Imagem agendamento.png') }}" alt="imagem-agendamentos">
    </div><!--img-agendamentos-->

</section><!--agendamentos-->

<section class="realizar">
    <h2>Confira todos os recursos do agendamento:</h2>
    <div class="card-agenda">
        <div class="card-escolher">
            <div class="icone">
             <i class="bi bi-calendar2-event"></i>
            </div>
            <h3>Datas</h3>
            <p>Escolha a data que melhor se adequa para a palestra.</p>
        </div>
        <div class="card-escolher">
            <div class="icone">
             <i class="bi bi-stopwatch"></i>
            </div>
            <h3>Horários</h3>
            <p>Selecione o horário mais conveniente para você.</p>
        </div>
        <div class="card-escolher">
            <div class="icone">
             <i class="bi bi-geo-alt"></i>
            </div>
            <h3>Local</h3>
            <p>Escolha o local onde deseja realizar a palestra.</p>
        </div>
        <div class="card-escolher">
            <div class="icone">
             <i class="bi bi-people"></i>
            </div>
            <h3>Público-Alvo</h3>
            <p>Defina o público que participará da palestra.</p>
        </div>
        <div class="card-escolher">
            <div class="icone">
             <i class="bi bi-card-checklist"></i>
            </div>
            <h3>Tema</h3>
            <p>Selecione o tema da palestra que deseja agendar.</p>
        </div>
    </div><!--card-agenda-->
</section><!--realizar-->
<section class="form-section">
    <form action="{{ url_for('agendamentos') }}" method="post">
        <section class="form-agendamentos" id="form">
            <h2>Preencha o formulário para agendar sua palestra</h2>
            <div class="campos-form">
                <div class="campo">
                    <label for="nome">Nome Completo</label>
                    <input type="text" id="nome" name="nome" required>
                </div>
                <div class="campo">
                    <label for="email">E-mail</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="campo">
                    <label for="telefone">Telefone</label>
                    <input type="tel" id="telefone" name="telefone" required>
                </div>
                <div class="campo">
                    <label for="data">Data da Palestra</label>
                    <input type="date" id="data" name="data" required>
                </div>
                <div class="campo">
                    <label for="horario">Horário</label>
                    <input type="time" id="horario" name="horario" required>
                </div>
                <div class="campo">
                    <label for="local">Local</label>
                    <input type="text" id="local" name="local" required>
                </div>
                <div class="campo">
                    <label for="publico">Público-Alvo</label>
                    <input type="text" id="publico" name="publico" required>
                </div>
                <div class="campo">
                    <label for="tema">Tema da Palestra</label>
                    <input type="text" id="tema" name="tema" required>
                </div>
            </div><!--campos-form-->
            <button type="submit" class="btn-enviar">Enviar Solicitação</button>
</section>
    </section><!--form-agendamentos-->
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Site da assessoria educacional Salvattore">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <title>{% block title %}Salvattore Assessoria{% endblock %}</title>
    <link rel="shortcut icon" href="static/images/SA-Photoroom.png" type="image/x-icon">
</head>
<body>
    <header>
        <img src="{{ url_for('static', filename='images/SA-Photoroom.png') }}" alt="logo">
        <input type="checkbox" id="menu-burger">
        <label for="menu-burger" class="menu-icon">
            <i class="fa-solid fa-bars"></i>
        </label>
        <nav>
            <ul>
                <li><a href="{{ url_for('pagina_principal') }}">Início</a></li>
                <li><a href="{{ url_for('contato') }}">Entre em contato</a></li>
                <li><a href="{{ url_for('agendamentos')}}">Agendamentos</a></li>
                <li><a href="{{ url_for('processos_seletivos') }}">Processos abertos</a></li>
                {% if 'usuario_logado' in session %}
                <li><a href="{{ url_for('admin.gerenciar_processos') }}">Gerenciar</a></li>
                {%endif%}
                {% if 'usuario_logado' in session %}
                    <li><a href="{{ url_for('admin.logout') }}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                {% else %}
                    <li><a href="{{ url_for('admin.login') }}"><i class="fa-solid fa-user"></i></a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for categoria, mensagem in messages %}
          <div class="alert alert-{{ categoria }}">
            {{ mensagem }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

        
        
        {%block content%}
        {%endblock%}
    </main>

    <footer id="rodape">
        <div class="logo_footer">
            <img src="{{ url_for('static', filename='images/SA footer-Photoroom.png') }}" alt="logo_footer" class="logo">
            <p>Transformando a gestão pública com inovação e eficiência</p>
            <a href="https://www.instagram.com/salvattore.assessoria?igsh=MWUwZnBxM3lmNXJ5bw=="><i class="bi bi-instagram"></i></a>
        </div><!--logo_footer-->
        <div class="contato">
            <h3>Contato</h3>
            <ul>
                <li>
                    <i class="bi bi-envelope"></i>
                    <a href="mailto:contato.salvattorepb@gmail.com" class="link-email"> contato.salvattorepb@gmail.com</a>
                </li>
                <li><i class="bi bi-telephone"></i>  +55 (83) 9 9922-9111</li>
                <li><i class="bi bi-geo-alt"></i>  Patos, Paraíba</li>
            </ul>
        </div><!--contato-->
        <hr>
        <div class="direitos">
            <p>&copy; 2026 Salvattore. Todos os direitos reservados</p>
        </div><!--direitos-->
    </footer>
</body>
</html>

templates/contato.html
{% extends "base.html" %}

{% block title %}
Contato
{% endblock %}

{% block content %}
    <section class="contato-section">
        <h2>Entre em Contato</h2>
        <form action="/contato" method="post" class="contato-form">
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" placeholder="Inisira seu nome" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" placeholder="Inisira seu melhor email" required>

            <label for="telefone">Telefone:</label>
            <input type="tel" id="telefone" name="telefone" placeholder="(xx) x xxxx-xxxx">

            <label for="assunto">Assunto:</label>
            <textarea id="assunto" name="assunto" placeholder="Do que se trata?" required></textarea>

            <button type="submit" class="contato-button">Enviar</button>
        </form>
    </section>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
Início
{% endblock %}

{% block content %}
    <section class="banner">
        <div class="banner">
            <h2>Salvattore Assessoria</h2>
            <p>Transformando a gestão pública com inovação e eficiência</p>
        </div><!-- banner-texto -->
    </section><!-- banner -->
    <section class="servicos" id="nossos_servicos">
        <h2>Nossos serviços</h2>
        <div class="card_container">
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Assessoria</h3>
                
                <p>Atuamos no diagnóstico de necessidades, na elaboração de projetos pedagógicos e na implementação de soluções alinhadas às demandas institucionais, sempre orientados por metodologias ativas e práticas contemporâneas de ensino-aprendizagem.</p>
            </div>
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Consultoria em Educação</h3>
                
                <p>Oferecemos assessoria e consultoria educacional para instituições públicas e privadas, apoiando o planejamento, a gestão e a inovação de processos educativos.</p>
            </div>
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Formação para professores</h3>
                
                <p>Formação continuada para professores, com foco na atualização pedagógica, inovação didática e uso de metodologias ativas. Nossos cursos articulam teoria e prática, promovendo aulas dinâmicas, significativas e alinhadas aos desafios atuais da educação, fortalecendo o protagonismo docente e a aprendizagem dos estudantes.</p>
            </div>
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Formação para Profissionais de Saúde</h3>
                
                <p>Cursos e capacitações voltados a profissionais da área da saúde, priorizando a qualificação técnica, científica e humana. São construídas sob demanda, com metodologias ativas e foco na prática profissional, contribuindo para a melhoria dos serviços de saúde e para a inovação nos processos de cuidado.</p>
            </div>
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Processos Seletivos</h3>
                
                <p>Elaboramos e executamos processos seletivos completos, desde o planejamento e construção dos instrumentos avaliativos até a aplicação e análise dos resultados. Nossos processos são personalizados, éticos e transparentes, garantindo rigor técnico, confiabilidade e alinhamento aos objetivos e perfis definidos pelas instituições contratantes.</p>
            </div>
            <div class="cards">
                <img src="static/images/SA só nome-Photoroom.png" alt="assinatura_salvattore" class="logo-card">
                <h3>Treinamentos</h3>
                
                <p>Implementamos soluções estratégicas de treinamento e desenvolvimento. Nossos programas são construídos sob medida, partindo de um diagnóstico preciso de necessidades e utilizando metodologias ativas que articulam a teoria à realidade prática. Focamos na criação de experiências de aprendizagem dinâmicas e significativas, que impulsionam a inovação, fortalecem competências técnicas e comportamentais, e geram impacto direto nos resultados institucionais.</p>
            </div>
        </div>
    </section><!-- serviços -->
    <section class="sobre-nos" id="sobre">
        <h2>Sobre nós</h2>
        <div class="sobre-nos">
            <div class="sobre-nos">
                <p>
                 Na Salvattore Assessoria, acreditamos que a gestão pública pode — e deve — ser sinônimo de eficiência, transparência e inovação. 
                 Somos uma consultoria especializada em elevar o padrão das políticas públicas no Brasil, 
                 unindo o rigor acadêmico à experiência prática de quem conhece os desafios do "chão da gestão".
                </p>
                <h3>Nossa Missão</h3>
                <p>
                 Transformar a administração pública através de soluções baseadas em evidências, capacitando líderes e 
                 otimizando processos para que o impacto chegue onde realmente importa: na vida do cidadão.
                </p>

                <h3>O que nos move?</h3>
                <p>
                 Não entregamos apenas diagnósticos; entregamos o "próximo nível". 
                 Isso significa que nossa atuação vai além do papel, 
                 focando na implementação real e na sustentabilidade das soluções propostas.Atuamos em três frentes principais:<br>
                 Inteligência Estratégica: Consultoria de alto impacto.<br>
                 Suporte Operacional: Assessoria técnica especializada.<br>
                 Legado de Conhecimento: Treinamentos que transformam servidores em agentes de inovação.
                </p>
            </div><!-- sobre-nos-texto -->
        </div><!-- sobre-nos-container -->
    </section><!-- Sobre-nos -->
{% endblock %}

templates/processos.html
{% extends "base.html" %}

{% block title %}
Processos seletivos
{% endblock %}

{% block content %}
<section class="contato-section">
    <h2>Procesos seletivos</h2>
    <div class="processos-container">
        {% if processos %}
            {% for processo in processos %}
                <div class="processos-cards">
                    <h3>{{ processo.titulo }}</h3>
                    <a href="{{ processo.url }}" target="_blank">Acesse aqui</a>
                </div>
            {% endfor %}
        {% else %}
            <div class="processos-cards">
                <h3>Sem processos abertos</h3>
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}